name: "promote testing to stable"
description: "Promote testing packages to stable."
inputs:
  artifactory_token:
    description: "Artifactory token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: https://centreon.jfrog.io
        JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}

    - name: Promote package
      run: |
        REPO="stable"
        echo "[DEBUG] - Promote to repository: $REPO "
        jf rt cp --dry-run rpm/centreon-business/ rpm-business/centreon-promote-test/
      shell: bash
