name: "promote testing to stable"
description: "Promote testing packages to stable."


runs:
  using: "composite"
  steps:
    - uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: https://centreon.jfrog.io
        JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}

    - name: Promote package
      run: |
        echo "[DEBUG] - Promote to repository: $REPO "
        jf rt cp --dry-run rpm/centreon-business/ rpm-business/
      shell: bash
