name: "promote testing to stable"
description: "Promote testing packages to stable."
inputs:
  artifactory_token:
    description: "Artifactory token"
    required: true
  module:
    description: "Module"
    required: true

runs:
  using: "composite"
  steps:
    - uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: https://centreon.jfrog.io
        JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}

    - name: Promote package
      run: |
        REPO="stable"
        echo "[DEBUG] - Promote to repository: $REPO"
        TARGET_PATH="rpm/standard/23.04/el8/stable/noarch/RPMS/"

        echo "[DEBUG] - Get path to dir with testing artifacts to promote to stable."
        SRC_PATH=$(jf rt s --include-dirs --fail-no-op rpm/standard/23.04/el8/testing/noarch/gorgone/centreon-gorgone-23.04.0-1 | jq -r '.[].path')

        echo "[DEBUG] - Promoting testing artifacts to stable."
        jf rt cp --recursive=false $SRC_PATH/* $TARGET_PATH/

      shell: bash
